name: dinq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.5.0
  iconsax: ^0.0.8
  http: ^1.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Correct assets section (only images/files)
  assets:
    - assets/images/

  # Correct fonts section (separate from assets)
  # fonts:
  #   - family: Inter
  #     # fonts:
  #     #   - asset: assets/fonts/Inter-Regular.ttf
  #     #   - asset: assets/fonts/Inter-Bold.ttf
  #     #     weight: 700
  #     #   - asset: assets/fonts/Inter-Italic.ttf
  #     #     style: italic