const String baseUrl = 'https://dineq.onrender.com/api/v1';
const String accessToken =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3MjMyNTM5LCJpc192ZXJpZmllZCI6ZmFsc2UsInJvbGUiOiJPV05FUiIsInN0YXR1cyI6IkFDVElWRSIsInN1YiI6IjY4Yjk1MDBjMWViZTUxNGI5OTQyNTIyNSJ9.gpff3SibwoGBThCFHw4Wl_R2ncIuoVTVKyRFZDBJH1I';
