# Air config to properly build and run the API from cmd/api on changes
# Generated to fix stale binary issue (previously: "no Go files in ...")

root = "."

[build]
# Windows executable output
bin = "tmp/main.exe"
cmd = "go build -o tmp/main.exe ./cmd/api"
# Exclude tmp build dir itself
exclude_dir = ["tmp"]
# Watch .go, .mod, .sum, .env
include_ext = ["go", "mod", "sum", "env"]
# Graceful delay (ms) before rebuilding after changes
delay = 500
# Send SIGINT then SIGKILL after timeout
kill_delay = 500

[log]
color = true

[misc]
clean_on_exit = true
