// Mocks generated by Mockito 5.4.6 from annotations
// in dinq/test/helper/mock/test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dinq/core/error/failures.dart' as _i12;
import 'package:dinq/core/network/network_info.dart' as _i17;
import 'package:dinq/features/restaurant_management/data/datasources/restaurant_remote_data_source.dart'
    as _i16;
import 'package:dinq/features/restaurant_management/domain/entities/category.dart'
    as _i14;
import 'package:dinq/features/restaurant_management/domain/entities/menu.dart'
    as _i3;
import 'package:dinq/features/restaurant_management/domain/entities/restaurant.dart'
    as _i13;
import 'package:dinq/features/restaurant_management/domain/entities/review.dart'
    as _i15;
import 'package:dinq/features/restaurant_management/domain/repositories/restaurant_repository.dart'
    as _i10;
import 'package:dio/src/adapter.dart' as _i5;
import 'package:dio/src/cancel_token.dart' as _i18;
import 'package:dio/src/dio.dart' as _i9;
import 'package:dio/src/dio_mixin.dart' as _i7;
import 'package:dio/src/options.dart' as _i4;
import 'package:dio/src/response.dart' as _i8;
import 'package:dio/src/transformer.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMenu_1 extends _i1.SmartFake implements _i3.Menu {
  _FakeMenu_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_2 extends _i1.SmartFake implements _i4.BaseOptions {
  _FakeBaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_3 extends _i1.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_4 extends _i1.SmartFake implements _i6.Transformer {
  _FakeTransformer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_5 extends _i1.SmartFake implements _i7.Interceptors {
  _FakeInterceptors_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_6<T1> extends _i1.SmartFake implements _i8.Response<T1> {
  _FakeResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_7 extends _i1.SmartFake implements _i9.Dio {
  _FakeDio_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestaurantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRepository extends _i1.Mock
    implements _i10.RestaurantRepository {
  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Restaurant>>>
  getRestaurants() =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurants, []),
            returnValue:
                _i11.Future<
                  _i2.Either<_i12.Failure, List<_i13.Restaurant>>
                >.value(
                  _FakeEither_0<_i12.Failure, List<_i13.Restaurant>>(
                    this,
                    Invocation.method(#getRestaurants, []),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Either<_i12.Failure, List<_i13.Restaurant>>
                >.value(
                  _FakeEither_0<_i12.Failure, List<_i13.Restaurant>>(
                    this,
                    Invocation.method(#getRestaurants, []),
                  ),
                ),
          )
          as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Restaurant>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i3.Menu>> getMenu(
    String? restaurantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [restaurantId]),
            returnValue: _i11.Future<_i2.Either<_i12.Failure, _i3.Menu>>.value(
              _FakeEither_0<_i12.Failure, _i3.Menu>(
                this,
                Invocation.method(#getMenu, [restaurantId]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i2.Either<_i12.Failure, _i3.Menu>>.value(
                  _FakeEither_0<_i12.Failure, _i3.Menu>(
                    this,
                    Invocation.method(#getMenu, [restaurantId]),
                  ),
                ),
          )
          as _i11.Future<_i2.Either<_i12.Failure, _i3.Menu>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i14.Category>>> getCategories(
    String? tabId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [tabId]),
            returnValue:
                _i11.Future<
                  _i2.Either<_i12.Failure, List<_i14.Category>>
                >.value(
                  _FakeEither_0<_i12.Failure, List<_i14.Category>>(
                    this,
                    Invocation.method(#getCategories, [tabId]),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Either<_i12.Failure, List<_i14.Category>>
                >.value(
                  _FakeEither_0<_i12.Failure, List<_i14.Category>>(
                    this,
                    Invocation.method(#getCategories, [tabId]),
                  ),
                ),
          )
          as _i11.Future<_i2.Either<_i12.Failure, List<_i14.Category>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i15.Review>>> getReviews(
    String? itemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [itemId]),
            returnValue:
                _i11.Future<_i2.Either<_i12.Failure, List<_i15.Review>>>.value(
                  _FakeEither_0<_i12.Failure, List<_i15.Review>>(
                    this,
                    Invocation.method(#getReviews, [itemId]),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Either<_i12.Failure, List<_i15.Review>>>.value(
                  _FakeEither_0<_i12.Failure, List<_i15.Review>>(
                    this,
                    Invocation.method(#getReviews, [itemId]),
                  ),
                ),
          )
          as _i11.Future<_i2.Either<_i12.Failure, List<_i15.Review>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<String>>> getUserImages(
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserImages, [slug]),
            returnValue:
                _i11.Future<_i2.Either<_i12.Failure, List<String>>>.value(
                  _FakeEither_0<_i12.Failure, List<String>>(
                    this,
                    Invocation.method(#getUserImages, [slug]),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Either<_i12.Failure, List<String>>>.value(
                  _FakeEither_0<_i12.Failure, List<String>>(
                    this,
                    Invocation.method(#getUserImages, [slug]),
                  ),
                ),
          )
          as _i11.Future<_i2.Either<_i12.Failure, List<String>>>);
}

/// A class which mocks [RestaurantRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRemoteDataSource extends _i1.Mock
    implements _i16.RestaurantRemoteDataSource {
  @override
  _i11.Future<List<_i13.Restaurant>> getRestaurants() =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurants, []),
            returnValue: _i11.Future<List<_i13.Restaurant>>.value(
              <_i13.Restaurant>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i13.Restaurant>>.value(
              <_i13.Restaurant>[],
            ),
          )
          as _i11.Future<List<_i13.Restaurant>>);

  @override
  _i11.Future<_i3.Menu> getMenu(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [restaurantId]),
            returnValue: _i11.Future<_i3.Menu>.value(
              _FakeMenu_1(this, Invocation.method(#getMenu, [restaurantId])),
            ),
            returnValueForMissingStub: _i11.Future<_i3.Menu>.value(
              _FakeMenu_1(this, Invocation.method(#getMenu, [restaurantId])),
            ),
          )
          as _i11.Future<_i3.Menu>);

  @override
  _i11.Future<List<_i14.Category>> getCategories(String? tabId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [tabId]),
            returnValue: _i11.Future<List<_i14.Category>>.value(
              <_i14.Category>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i14.Category>>.value(
              <_i14.Category>[],
            ),
          )
          as _i11.Future<List<_i14.Category>>);

  @override
  _i11.Future<List<_i15.Review>> getReviews(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [itemId]),
            returnValue: _i11.Future<List<_i15.Review>>.value(<_i15.Review>[]),
            returnValueForMissingStub: _i11.Future<List<_i15.Review>>.value(
              <_i15.Review>[],
            ),
          )
          as _i11.Future<List<_i15.Review>>);

  @override
  _i11.Future<List<String>> getUserImages(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getUserImages, [slug]),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i11.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i11.Future<List<String>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i17.NetworkInfo {
  @override
  _i11.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i9.Dio {
  @override
  _i4.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_2(this, Invocation.getter(#options)),
            returnValueForMissingStub: _FakeBaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i4.BaseOptions);

  @override
  _i5.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_3(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
            returnValueForMissingStub: _FakeHttpClientAdapter_3(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i5.HttpClientAdapter);

  @override
  _i6.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_4(
              this,
              Invocation.getter(#transformer),
            ),
            returnValueForMissingStub: _FakeTransformer_4(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i6.Transformer);

  @override
  _i7.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_5(
              this,
              Invocation.getter(#interceptors),
            ),
            returnValueForMissingStub: _FakeInterceptors_5(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i7.Interceptors);

  @override
  set options(_i4.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i6.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i8.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i18.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i18.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    _i18.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i18.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i18.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> fetch<T>(_i4.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i9.Dio clone({
    _i4.BaseOptions? options,
    _i7.Interceptors? interceptors,
    _i5.HttpClientAdapter? httpClientAdapter,
    _i6.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_7(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
            returnValueForMissingStub: _FakeDio_7(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i9.Dio);
}
