// Mocks generated by Mockito 5.4.6 from annotations
// in dinq/test/helper/mock/test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dinq/core/error/failures.dart' as _i13;
import 'package:dinq/core/network/network_info.dart' as _i18;
import 'package:dinq/features/dinq/restaurant_management/data/datasources/restaurant_remote_data_source.dart'
    as _i17;
import 'package:dinq/features/dinq/restaurant_management/data/model/restaurant_model.dart'
    as _i14;
import 'package:dinq/features/dinq/restaurant_management/domain/entities/category.dart'
    as _i15;
import 'package:dinq/features/dinq/restaurant_management/domain/entities/menu.dart'
    as _i4;
import 'package:dinq/features/dinq/restaurant_management/domain/entities/restaurant.dart'
    as _i3;
import 'package:dinq/features/dinq/restaurant_management/domain/entities/review.dart'
    as _i16;
import 'package:dinq/features/dinq/restaurant_management/domain/repositories/restaurant_repository.dart'
    as _i11;
import 'package:dio/src/adapter.dart' as _i6;
import 'package:dio/src/cancel_token.dart' as _i19;
import 'package:dio/src/dio.dart' as _i10;
import 'package:dio/src/dio_mixin.dart' as _i8;
import 'package:dio/src/options.dart' as _i5;
import 'package:dio/src/response.dart' as _i9;
import 'package:dio/src/transformer.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRestaurant_1 extends _i1.SmartFake implements _i3.Restaurant {
  _FakeRestaurant_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMenu_2 extends _i1.SmartFake implements _i4.Menu {
  _FakeMenu_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_3 extends _i1.SmartFake implements _i5.BaseOptions {
  _FakeBaseOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_4 extends _i1.SmartFake
    implements _i6.HttpClientAdapter {
  _FakeHttpClientAdapter_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_5 extends _i1.SmartFake implements _i7.Transformer {
  _FakeTransformer_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_6 extends _i1.SmartFake implements _i8.Interceptors {
  _FakeInterceptors_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_7<T1> extends _i1.SmartFake implements _i9.Response<T1> {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_8 extends _i1.SmartFake implements _i10.Dio {
  _FakeDio_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestaurantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRepository extends _i1.Mock
    implements _i11.RestaurantRepository {
  MockRestaurantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>> createRestaurant(
    _i14.RestaurantModel? restaurant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRestaurant, [restaurant]),
            returnValue:
                _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>.value(
                  _FakeEither_0<_i13.Failure, _i3.Restaurant>(
                    this,
                    Invocation.method(#createRestaurant, [restaurant]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<_i3.Restaurant>>> getRestaurants({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurants, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue:
                _i12.Future<
                  _i2.Either<_i13.Failure, List<_i3.Restaurant>>
                >.value(
                  _FakeEither_0<_i13.Failure, List<_i3.Restaurant>>(
                    this,
                    Invocation.method(#getRestaurants, [], {
                      #page: page,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, List<_i3.Restaurant>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>> getRestaurantBySlug(
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantBySlug, [slug]),
            returnValue:
                _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>.value(
                  _FakeEither_0<_i13.Failure, _i3.Restaurant>(
                    this,
                    Invocation.method(#getRestaurantBySlug, [slug]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>> updateRestaurant(
    _i14.RestaurantModel? restaurant,
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRestaurant, [restaurant, slug]),
            returnValue:
                _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>.value(
                  _FakeEither_0<_i13.Failure, _i3.Restaurant>(
                    this,
                    Invocation.method(#updateRestaurant, [restaurant, slug]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, _i3.Restaurant>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, void>> deleteRestaurant(
    String? restaurantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRestaurant, [restaurantId]),
            returnValue: _i12.Future<_i2.Either<_i13.Failure, void>>.value(
              _FakeEither_0<_i13.Failure, void>(
                this,
                Invocation.method(#deleteRestaurant, [restaurantId]),
              ),
            ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, void>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i4.Menu>> getMenu(
    String? restaurantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [restaurantId]),
            returnValue: _i12.Future<_i2.Either<_i13.Failure, _i4.Menu>>.value(
              _FakeEither_0<_i13.Failure, _i4.Menu>(
                this,
                Invocation.method(#getMenu, [restaurantId]),
              ),
            ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, _i4.Menu>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, void>> updateMenu(_i4.Menu? menu) =>
      (super.noSuchMethod(
            Invocation.method(#updateMenu, [menu]),
            returnValue: _i12.Future<_i2.Either<_i13.Failure, void>>.value(
              _FakeEither_0<_i13.Failure, void>(
                this,
                Invocation.method(#updateMenu, [menu]),
              ),
            ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, void>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<_i15.Category>>> deleteReview(
    String? tabId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [tabId]),
            returnValue:
                _i12.Future<
                  _i2.Either<_i13.Failure, List<_i15.Category>>
                >.value(
                  _FakeEither_0<_i13.Failure, List<_i15.Category>>(
                    this,
                    Invocation.method(#getCategories, [tabId]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, List<_i15.Category>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<_i16.Review>>> getReviews(
    String? itemId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [itemId]),
            returnValue:
                _i12.Future<_i2.Either<_i13.Failure, List<_i16.Review>>>.value(
                  _FakeEither_0<_i13.Failure, List<_i16.Review>>(
                    this,
                    Invocation.method(#getReviews, [itemId]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, List<_i16.Review>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<String>>> getUserImages(
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserImages, [slug]),
            returnValue:
                _i12.Future<_i2.Either<_i13.Failure, List<String>>>.value(
                  _FakeEither_0<_i13.Failure, List<String>>(
                    this,
                    Invocation.method(#getUserImages, [slug]),
                  ),
                ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, List<String>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, void>> updateItem() =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, []),
            returnValue: _i12.Future<_i2.Either<_i13.Failure, void>>.value(
              _FakeEither_0<_i13.Failure, void>(
                this,
                Invocation.method(#updateItem, []),
              ),
            ),
          )
          as _i12.Future<_i2.Either<_i13.Failure, void>>);
}

/// A class which mocks [RestaurantRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRemoteDataSource extends _i1.Mock
    implements _i17.RestaurantRemoteDataSource {
  MockRestaurantRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i3.Restaurant> createRestaurant(
    _i14.RestaurantModel? restaurant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRestaurant, [restaurant]),
            returnValue: _i12.Future<_i3.Restaurant>.value(
              _FakeRestaurant_1(
                this,
                Invocation.method(#createRestaurant, [restaurant]),
              ),
            ),
          )
          as _i12.Future<_i3.Restaurant>);

  @override
  _i12.Future<List<_i3.Restaurant>> getRestaurants({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurants, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i12.Future<List<_i3.Restaurant>>.value(
              <_i3.Restaurant>[],
            ),
          )
          as _i12.Future<List<_i3.Restaurant>>);

  @override
  _i12.Future<_i3.Restaurant> getRestaurantBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantBySlug, [slug]),
            returnValue: _i12.Future<_i3.Restaurant>.value(
              _FakeRestaurant_1(
                this,
                Invocation.method(#getRestaurantBySlug, [slug]),
              ),
            ),
          )
          as _i12.Future<_i3.Restaurant>);

  @override
  _i12.Future<_i3.Restaurant> updateRestaurant(
    _i14.RestaurantModel? restaurant,
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRestaurant, [restaurant, slug]),
            returnValue: _i12.Future<_i3.Restaurant>.value(
              _FakeRestaurant_1(
                this,
                Invocation.method(#updateRestaurant, [restaurant, slug]),
              ),
            ),
          )
          as _i12.Future<_i3.Restaurant>);

  @override
  _i12.Future<void> deleteRestaurant(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRestaurant, [restaurantId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.Menu> getMenu(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#getMenu, [restaurantId]),
            returnValue: _i12.Future<_i4.Menu>.value(
              _FakeMenu_2(this, Invocation.method(#getMenu, [restaurantId])),
            ),
          )
          as _i12.Future<_i4.Menu>);

  @override
  _i12.Future<List<_i15.Category>> getCategories(String? tabId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [tabId]),
            returnValue: _i12.Future<List<_i15.Category>>.value(
              <_i15.Category>[],
            ),
          )
          as _i12.Future<List<_i15.Category>>);

  @override
  _i12.Future<List<_i16.Review>> getReviews(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [itemId]),
            returnValue: _i12.Future<List<_i16.Review>>.value(<_i16.Review>[]),
          )
          as _i12.Future<List<_i16.Review>>);

  @override
  _i12.Future<List<String>> getUserImages(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getUserImages, [slug]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i18.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i10.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_3(this, Invocation.getter(#options)),
          )
          as _i5.BaseOptions);

  @override
  _i6.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_4(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i6.HttpClientAdapter);

  @override
  _i7.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_5(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i7.Transformer);

  @override
  _i8.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_6(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i8.Interceptors);

  @override
  set options(_i5.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i6.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i7.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i9.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i19.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i19.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i12.Future<_i9.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<dynamic>>);

  @override
  _i12.Future<_i9.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    _i19.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i12.Future<_i9.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<dynamic>>);

  @override
  _i12.Future<_i9.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i19.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i19.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i12.Future<_i9.Response<T>> fetch<T>(_i5.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i12.Future<_i9.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i12.Future<_i9.Response<T>>);

  @override
  _i10.Dio clone({
    _i5.BaseOptions? options,
    _i8.Interceptors? interceptors,
    _i6.HttpClientAdapter? httpClientAdapter,
    _i7.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_8(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i10.Dio);
}
